CMproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('classmanager.urls')),
    path('',include('accounts.urls')),
    path('',include('accountsclassroom.urls')),
    path('',include('classreport.urls')),
    path('password_reset/',
         auth_views.PasswordResetView.as_view(
             template_name="password_reset.html"),
         name='password_reset'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name="password_reset_sent.html"),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(
             template_name="password_reset_form.html"),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name="password_reset_done.html"),
         name='password_reset_complete'),
]

accounts/urls.py
from django.urls import path
from .import views
from django.contrib.auth import views as auth_views
app_name = 'accounts'
urlpatterns = [
    path('signup/',views.SignUpView.as_view(),name='signup'),
    path('signup_success/',views.SignUpSuccessView.as_view(),name='signup_success'),
    path('login',views.LoginView.as_view(),name='login'),
    path('logout/',views.LogoutView.as_view(),name='logout'),
]

classmanager/urls.py
from django.urls import path
from .import views

app_name='classmanager'
urlpatterns = [
    path('manager',views.IndexView.as_view(),name='manager'),
    path('',views.LoginSelectView.as_view(),name='loginselect'),
    path('assessmentlist',views.AssessmentListView.as_view(),name='assessmentlist'),
    path('setting',views.SettingView.as_view(),name='setting'),
    path('superenglishlist',views.SuperEnglishlistView.as_view(),name='superenglishlist'),
    path('studentregistration',views.StudentRegistrationView.as_view(),name='studentregistration'),
    path('studentlist',views.StudentListView.as_view(),name='studentlist'),
    path('teacherregistration',views.TeacherRegistrationView.as_view(),name='teacherregistration'),
    path('teacherlist',views.TeacherListView.as_view(),name='teacherlist'),
    path('classroomregistration',views.ClassroomRegistrationView.as_view(),name='classroomregistration'),
    path('classroomlist',views.ClassroomListView.as_view(),name='classroomlist'),
    path('lessonlist',views.LessonListView.as_view(),name='lessonlist'),
    path('timetable',views.TimetableView.as_view(),name='timetable'),
    path('api/printstudentlist/get/', views.ajax_get_printstudentlist, name='ajax_get_printstudentlist'),
    path('api/deletestudentlist/get/', views.ajax_get_deletestudentlist, name='ajax_get_deletestudentlist'),
    path('api/createstudentlist/get/', views.ajax_get_createstudentlist, name='ajax_get_createstudentlist'),
    path('api/updatastudentlist/get/', views.ajax_get_updatastudentlist, name='ajax_get_updatastudentlist'),
    path('api/updatastudentschool/get/', views.ajax_get_updatastudentschool, name='ajax_get_updatastudentschool'),
    path('ajax/delete_student_school/', views.ajax_delete_student_school, name='ajax_delete_student_school'),
    path('ajax/create_student_school/', views.ajax_create_student_school, name='ajax_create_student_school'),
    path('create_subject/', views.ajax_create_subject, name='ajax_create_subject'),
    path('ajax_get_printsubjectlist/', views.ajax_get_printsubjectlist, name='ajax_get_printsubjectlist'),
    path('ajax/get_subjects/', views.get_subjects, name='get_subjects'),
    path('ajax_get_printclassroomlist/', views.ajax_get_printclassroomlist, name='ajax_get_printclassroomlist'),
    path('ajax/create_teacher/', views.ajax_create_teacher, name='ajax_create_teacher'),
    path('ajax_get_teacherlist/', views.ajax_get_teacherlist, name='ajax_get_teacherlist'),
    path('ajax_get_update_teacher/', views.ajax_get_update_teacher, name='ajax_get_update_teacher'),
    path('ajax_get_deleteteacherlist/', views.ajax_get_deleteteacherlist, name='ajax_get_deleteteacherlist'),
    path('update-class-schedule/', views.update_class_schedule, name='update_class_schedule'),
    path('create-class-schedule/', views.create_class_schedule, name='create_class_schedule'),
    path('get-class-schedules/', views.get_class_schedules, name='get_class_schedules'),
    path('ajax_get_printtimetableoption/', views.ajax_get_printtimetableoption, name='ajax_get_printtimetableoption'),
    path('ajax/create/period/', views.ajax_create_period, name='ajax_create_period'),
    path('ajax/get/period_list/', views.ajax_get_printperiodlist, name='ajax_get_printperiodlist'),
    path('classroom_users_endpoint/', views.classroom_users_endpoint, name='classroom_users_endpoint'),
    path('api/get-reports/', views.get_reports, name='get_reports'),
    path('approve_report/', views.approve_report, name='approve_report'),
    path('update_class_schedule/', views.update_class_schedule, name='update_class_schedule'),
    path('delete_class_schedule/', views.delete_class_schedule, name='delete_class_schedule'),
    path('ajax/update-classroom/', views.update_classroom, name='update_classroom'),
    path('ajax/delete-classroom/', views.delete_classroom, name='delete_classroom'),
    path('ajax/ajax_update_subject/', views.ajax_update_subject, name='ajax_update_subject'),
    path('ajax/delete-subject/', views.delete_subject, name='ajax_delete_subject'),
    path('ajax/update_period/', views.update_period, name='update_period'),
    path('ajax/delete_period/', views.delete_period, name='delete_period'),
    path('get_student_subjects/<int:student_id>/', views.get_student_subjects, name='get_student_subjects'),
    path('get-report-detail/', views.get_report_detail, name='get_report_detail'),
    path('get-update_report/', views.update_report, name='update_report'),
    path('update_settings/', views.update_settings, name='update_settings'),
    path('schoollist/', views.SchoollistView.as_view(), name='schoollist'),
    path('ajax_delete_school/', views.ajax_delete_school, name='ajax_delete_school'),
    path('ajax_update_school/', views.ajax_update_school, name='ajax_update_school'),
    path('ajax_create_school/', views.ajax_create_school, name='ajax_create_school'),
    path('ajax_get_schoollist/', views.ajax_get_schoollist, name='ajax_get_schoollist'),
    path('ajax/get-schools/', views.get_schools_by_stage, name='get_schools'),
    path('delete_last_phone/', views.delete_last_phone, name='delete_last_phone'),
    path('register_parent_category/', views.register_parent_category, name='register_parent_category'),
    path('register_category/', views.register_category, name='register_category'),
    path('register_english_word/', views.register_english_word, name='register_english_word'),
    path('get_parent_categories/', views.get_parent_categories, name='get_parent_categories'),
    path('get_categories/', views.get_categories, name='get_categories'),
    path('get_english_words/', views.get_english_words, name='get_english_words'),
    path('upload_excel/', views.upload_excel, name='upload_excel'),
    path('get_parent_categories/', views.get_parent_categories, name='get_parent_categories'),
    path('get_categories/', views.get_categories, name='get_categories'),
    path('get_english_words/', views.get_english_words, name='get_english_words'),
    path('update_parent_category/', views.update_parent_category, name='update_parent_category'),
    path('delete_parent_category/', views.delete_parent_category, name='delete_parent_category'),
    path('update_category/', views.update_category, name='update_category'),
    path('delete_category/', views.delete_category, name='delete_category'),
    path('update_english_word/', views.update_english_word, name='update_english_word'),
    path('delete_english_word/', views.delete_english_word, name='delete_english_word'),


   

    
  
]
    

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from accountsclassroom.models import ClassroomUser

class ManagerUser(AbstractUser):
    post=models.CharField(max_length=200,blank=True,null=True)
    send_email_address = models.EmailField(verbose_name='配信元メールアドレス', blank=True, null=True)
    email_setting= models.BooleanField(
        default=True
    )


# Create your models here.


class ManagerClassroom(models.Model):

    manager=models.ForeignKey(
        ManagerUser,
        verbose_name='マネージャー',
        on_delete=models.CASCADE, blank=True, null=True,
    )
    classroom=models.ForeignKey(
        ClassroomUser,
        verbose_name='教室',
        on_delete=models.CASCADE, blank=True, null=True,
    )

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import ManagerUser

class ManagerUserCreationForm(UserCreationForm):
    class Meta:
        model = ManagerUser
        fields = ('username','email','password1','password2')

accounts/views.py
from django.shortcuts import render
from django.views.generic import CreateView,TemplateView
from .forms import ManagerUserCreationForm
from django.urls import reverse_lazy
from urllib.parse import urlparse, urlunparse
from django.conf import settings
from django.contrib.auth import REDIRECT_FIELD_NAME, get_user_model
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import (
    AuthenticationForm,
    PasswordChangeForm,
    PasswordResetForm,
    SetPasswordForm,
)
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.shortcuts import get_current_site
from django.core.exceptions import ImproperlyConfigured, ValidationError
from django.http import HttpResponseRedirect, QueryDict
from django.shortcuts import resolve_url
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.utils.http import url_has_allowed_host_and_scheme, urlsafe_base64_decode
from django.utils.translation import gettext_lazy as _
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView
from .models import ManagerUser
from django.contrib.auth.views import LoginView,LogoutView

UserModel = ManagerUser.objects
# Create your views here.

from django.shortcuts import render
from django.views.generic import CreateView,TemplateView
from .forms import ManagerUserCreationForm
from django.urls import reverse_lazy
# Create your views here.

class SignUpView(CreateView):
    form_class=ManagerUserCreationForm
    template_name="signup.html"
    success_url=reverse_lazy('accounts:signup_success')

    def form_valid(self,form):
        user=form.save()
        self.object=user
        return super().form_valid(form)

class SignUpSuccessView(TemplateView):
    template_name="signup_success.html"


class LoginView(LoginView):
    form_class = AuthenticationForm
    authentication_form = None
    template_name = "login.html"
    redirect_authenticated_user = False
    extra_context = None

    @method_decorator(sensitive_post_parameters())
    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        if self.redirect_authenticated_user and self.request.user.is_authenticated:
            redirect_to = self.get_success_url()
            if redirect_to == self.request.path:
                raise ValueError(
                    "Redirection loop for authenticated user detected. Check that "
                    "your LOGIN_REDIRECT_URL doesn't point to a login page."
                )
            return HttpResponseRedirect(redirect_to)
        return super().dispatch(request, *args, **kwargs)

    def get_default_redirect_url(self):
        """Return the default redirect URL."""
        if self.next_page:
            return resolve_url(self.next_page)
        else:
            return resolve_url(settings.LOGIN_REDIRECT_URL)

    def get_form_class(self):
        return self.authentication_form or self.form_class

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["request"] = self.request
        return kwargs

    def form_valid(self, form):
        """Security check complete. Log the user in."""
        auth_login(self.request, form.get_user(), 'accounts.backends.ManagerAuthBackend')
        return HttpResponseRedirect(self.get_success_url())

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        current_site = get_current_site(self.request)
        context.update(
            {
                self.redirect_field_name: self.get_redirect_url(),
                "site": current_site,
                "site_name": current_site.name,
                **(self.extra_context or {}),
            }
        )
        return context


class LogoutView(LogoutView):
    """
    Log out the user and display the 'You are logged out' message.
    """

    http_method_names = ["post", "options"]
    template_name = "logout.html"
    extra_context = None

    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        """Logout may be done via POST."""
        auth_logout(request)
        redirect_to = self.get_success_url()
        if redirect_to != request.get_full_path():
            # Redirect to target page once the session has been cleared.
            return HttpResponseRedirect(redirect_to)
        return super().get(request, *args, **kwargs)

    def get_default_redirect_url(self):
        """Return the default redirect URL."""
        if self.next_page:
            return resolve_url(self.next_page)
        elif settings.LOGOUT_REDIRECT_URL:
            return resolve_url(settings.LOGOUT_REDIRECT_URL)
        else:
            return self.request.path

accounts/templates/login.html
{% extends 'baselite.html' %}
{% load static %}
{% block content %}
  
    <link rel="icon" type="imge/x-icon"
        href={% static 'assets/favicon.ico' %} />
        
    

    

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

     
    </style>

    
    <!-- Custom styles for this template -->
    <link href={% static "css/signin.css"%} rel="stylesheet">
</head>
    <body class="text-center">
        <main class="form-signin ">
            {% if form.errors %}
              <p style="color: red">ユーザー名とパスワードが一致しません</p>
            {% endif %}
            <form method="post" class="text-center">
            {% csrf_token %}
                <!-- <img class="mb-4"
                    src={% static "img/bootstrap-logo.svg" %}
                    alt="" width="72"
                    height="57"> -->
                <h1 class="h3 mb-3 fw-normal">管理者アカウントでログイン</h1>
                <label for="Username" class="visually-hidden ">
                    User name</label>
                   
                <input type="text"
                name="username"
                id="id_username"
                maxlength="150"
                autocapitalize="none"
                autocomplete="username"
                class="form-control"
                style="width: 20rem; margin: 0 auto;"
                placeholder="ユーザー名"
                required autofocus>
            
                <label for="Password" class="visually-hidden">
                Password</label>
                <input type="password"
                name="password"
                id="id_password"
                autocomplete="current-password"
                class="form-control"
                style="width: 20rem; margin: 0 auto;"
                placeholder="パスワード"
                required autofocus>
                <input class="w-90 btn btn-lg btn-primary m-3"
                type="submit"
                value="ログイン">
               
                <br><br>
                <p><a href="{% url 'password_reset' %}">パスワードを忘れましたか</a><P>
                <p><a href="{% url 'accounts:signup' %}">新規登録</a><P>

                <input type="hidden"
                    name="next"
                    value="{% url 'classmanager:manager' %}">
            </form>
        </main>
    </body>
{% endblock %}

accounts/templates/logout.html
{% extends 'baselite.html' %}
{% block title %}Log out{% endblock %}
    {% block content %}
    <div class="container">
        <div class="row">
            <div class="col offset-4 py-4">
            <h3>ログアウトしました</h3>
            <p><a href="{% url 'classmanager:loginselect' %}">トップページ</a><p>
        {% endblock %}

accounts/templates/password_reset.html
{% extends 'baselite.html' %}
{% block title %}Reset password{% endblock %}
    {% block content %}
    <div class="container">
        <div class="row">
            <div class="col py-4">
                <hr>
                <h3>パスワードをリセットしますか
                <p>
                登録済みのメールアドレスを入力して下さいパスワードリセットのリンクを記載したメールをすぐにお届けします
                </p>
                <br>
                <form action="" method="POST" class="text-center">
                    {% csrf_token %}
                    {{form}}
                    <input type="submit" value="メールを受け取る"/><br>
                </form>
                <br>
                <a href="{% url 'classmanager:loginselect' %}">Photo Gallery</a>
                <hr>
            </div>
        </div>
    </div>
 {% endblock %}

accounts/templates/password_reset_done.html
<!doctype html>
<html lang="ja".
    <head>
        <style>
            .pad{
                background-color: lavender;
                border: solid 2px;
                padding-top: 30px;
                padding-bottom: 50px;
                padding-left: 100px;
                margin-top: 50px;
                margin-right: 70px;
                margin-left: 70px;
                }
        </style>
    </head>
    <body>
        <div class="pad">
            <h2>パスワードがリセットされました</h2>
            <p>
            Your Password has been set. You may gto ahead and login
            </p>
            <br>
            <a href="{% url 'photo:index' %}">Photo Galleryのトップページ</a>
        </div>
    </body>
</html>

accounts/templates/password_reset_form.html
<!doctype html>
<html lang="ja">
    <head>
        <style>
            .pad{
                background-color: lavender;
                border: solid 2px;
                padding-top: 30px;
                padding-bottom: 50px;
                padding-left: 100px;
                margin-top: 50px;
                margin-right: 70px;
                margin-left: 70px;
                }
            </style>
        </head>
        <body>
            <div class="pad">
                <h2>Photo Gallery</h2>
                <h4>新しいパスワードを入力してください。これにより正しく入力できたことが確認されます</h4>
                <br />
                <form action="" method="POST">
                    {% csrf_token %}
                    {{form}}
                <input type="submit" value="パスワードリセット"/>
            </form>
        </div>
    </body>
</html>

accounts/templates/password_reset_sent.html
{% extends 'baselite.html' %}
{% block title %}Send password reset{% endblock %}
    {% block content %}
    <hr>
    <div class="container">
        <div class="row">
            <div class="col offset-2 py-4">
                <h5>パスワードのリセット手順をメールで送信しました</h5>
            <br>
            <h6>
            メールが届かない場合は登録済みのメールアドレスであるかを確認し迷惑メールフォルダも確認してください</h6>
            <br>
            <a href="{% url 'classmanager:loginselect' %}">photo Gallery</a>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/signup.html
{% extends 'baselite.html' %}
{% block title %}Sign up{% endblock %}
    {% block content %}
    
    <hr>
    <div class="container">
        <div class="row">
            <div class="col offset-2">
                <h3>サインアップ</h3>
                <form method = "post">
                    {% csrf_token %}
                    {% for field in form %}
                    <p>
                        {{field.label_tag}}<br>
                        {{field}}
                        {% if field.help_text %}
                        <small style="color: grey">{{field.help_text}}</small>
                        {% endif %}
                        {% for error in field.errors %}
                        <p style="color:red">{{error}}</p>
                        {% endfor %}
                    </p>
                    {% endfor %}    
                    <p style="color:red">
                        メールアドレスはパスワードをリセットする際に必要になります
                    </p>
                    <input type="submit" value="Sign up">                    
                </form>
                <br>
                <p><a href="{% url 'classmanager:loginselect' %}">
                    登録をやめてトップに戻る
                </a>
                </p>
            </div>
        </div>
    </div>
    {% endblock %}

accounts/templates/signup_success.html
{% extends 'baselite.html' %}
{% block title %}Registration Complete{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col offset-4 py-4">
            <h3>登録が完了しました</h3>
            <p><a href="{% url 'accounts:login' %}">ログインはこちら</a></p>
        </div>
    </div>
</div>
{% endblock %}