CMproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('classmanager.urls')),
    path('',include('accounts.urls')),
    path('',include('accountsclassroom.urls')),
    path('',include('classreport.urls')),
    path('password_reset/',
         auth_views.PasswordResetView.as_view(
             template_name="password_reset.html"),
         name='password_reset'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name="password_reset_sent.html"),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(
             template_name="password_reset_form.html"),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name="password_reset_done.html"),
         name='password_reset_complete'),
]

accounts/urls.py
from django.urls import path
from .import views
from django.contrib.auth import views as auth_views
app_name = 'accounts'
urlpatterns = [
    path('signup/',views.SignUpView.as_view(),name='signup'),
    path('signup_success/',views.SignUpSuccessView.as_view(),name='signup_success'),
    path('login',views.LoginView.as_view(),name='login'),
    path('logout/',views.LogoutView.as_view(),name='logout'),
]

accountsclassroom/urls.py
from django.urls import path
from .import views
from django.contrib.auth import views as auth_views
app_name = 'accountsclassroom'
urlpatterns = [
    path('signup_classroom/',views.SignUpClassroomView.as_view(),name='signup_classroom'),
    path('signup_success_classroom/',views.SignUpSuccessClassroomView.as_view(),name='signup_success_classroom'),
    path('login_classroom',views.LoginClassroomView.as_view(),name='login_classroom'),
    path('login_classroom_game',views.LoginClassroomGameView.as_view(),name='login_classroom_game'),
    path('logout_classroom/',views.LogoutClassroomView.as_view(),name='logout_classroom'),
]

classmanager/urls.py
from django.urls import path
from .import views

app_name='classmanager'
urlpatterns = [
    path('manager',views.IndexView.as_view(),name='manager'),
    path('',views.LoginSelectView.as_view(),name='loginselect'),
    path('assessmentlist',views.AssessmentListView.as_view(),name='assessmentlist'),
    path('setting',views.SettingView.as_view(),name='setting'),
    path('superenglishlist',views.SuperEnglishlistView.as_view(),name='superenglishlist'),
    path('studentregistration',views.StudentRegistrationView.as_view(),name='studentregistration'),
    path('studentlist',views.StudentListView.as_view(),name='studentlist'),
    path('teacherregistration',views.TeacherRegistrationView.as_view(),name='teacherregistration'),
    path('teacherlist',views.TeacherListView.as_view(),name='teacherlist'),
    path('classroomregistration',views.ClassroomRegistrationView.as_view(),name='classroomregistration'),
    path('classroomlist',views.ClassroomListView.as_view(),name='classroomlist'),
    path('lessonlist',views.LessonListView.as_view(),name='lessonlist'),
    path('timetable',views.TimetableView.as_view(),name='timetable'),
    path('api/printstudentlist/get/', views.ajax_get_printstudentlist, name='ajax_get_printstudentlist'),
    path('api/deletestudentlist/get/', views.ajax_get_deletestudentlist, name='ajax_get_deletestudentlist'),
    path('api/createstudentlist/get/', views.ajax_get_createstudentlist, name='ajax_get_createstudentlist'),
    path('api/updatastudentlist/get/', views.ajax_get_updatastudentlist, name='ajax_get_updatastudentlist'),
    path('api/updatastudentschool/get/', views.ajax_get_updatastudentschool, name='ajax_get_updatastudentschool'),
    path('ajax/delete_student_school/', views.ajax_delete_student_school, name='ajax_delete_student_school'),
    path('ajax/create_student_school/', views.ajax_create_student_school, name='ajax_create_student_school'),
    path('create_subject/', views.ajax_create_subject, name='ajax_create_subject'),
    path('ajax_get_printsubjectlist/', views.ajax_get_printsubjectlist, name='ajax_get_printsubjectlist'),
    path('ajax/get_subjects/', views.get_subjects, name='get_subjects'),
    path('ajax_get_printclassroomlist/', views.ajax_get_printclassroomlist, name='ajax_get_printclassroomlist'),
    path('ajax/create_teacher/', views.ajax_create_teacher, name='ajax_create_teacher'),
    path('ajax_get_teacherlist/', views.ajax_get_teacherlist, name='ajax_get_teacherlist'),
    path('ajax_get_update_teacher/', views.ajax_get_update_teacher, name='ajax_get_update_teacher'),
    path('ajax_get_deleteteacherlist/', views.ajax_get_deleteteacherlist, name='ajax_get_deleteteacherlist'),
    path('update-class-schedule/', views.update_class_schedule, name='update_class_schedule'),
    path('create-class-schedule/', views.create_class_schedule, name='create_class_schedule'),
    path('get-class-schedules/', views.get_class_schedules, name='get_class_schedules'),
    path('ajax_get_printtimetableoption/', views.ajax_get_printtimetableoption, name='ajax_get_printtimetableoption'),
    path('ajax/create/period/', views.ajax_create_period, name='ajax_create_period'),
    path('ajax/get/period_list/', views.ajax_get_printperiodlist, name='ajax_get_printperiodlist'),
    path('classroom_users_endpoint/', views.classroom_users_endpoint, name='classroom_users_endpoint'),
    path('api/get-reports/', views.get_reports, name='get_reports'),
    path('approve_report/', views.approve_report, name='approve_report'),
    path('update_class_schedule/', views.update_class_schedule, name='update_class_schedule'),
    path('delete_class_schedule/', views.delete_class_schedule, name='delete_class_schedule'),
    path('ajax/update-classroom/', views.update_classroom, name='update_classroom'),
    path('ajax/delete-classroom/', views.delete_classroom, name='delete_classroom'),
    path('ajax/ajax_update_subject/', views.ajax_update_subject, name='ajax_update_subject'),
    path('ajax/delete-subject/', views.delete_subject, name='ajax_delete_subject'),
    path('ajax/update_period/', views.update_period, name='update_period'),
    path('ajax/delete_period/', views.delete_period, name='delete_period'),
    path('get_student_subjects/<int:student_id>/', views.get_student_subjects, name='get_student_subjects'),
    path('get-report-detail/', views.get_report_detail, name='get_report_detail'),
    path('get-update_report/', views.update_report, name='update_report'),
    path('update_settings/', views.update_settings, name='update_settings'),
    path('schoollist/', views.SchoollistView.as_view(), name='schoollist'),
    path('ajax_delete_school/', views.ajax_delete_school, name='ajax_delete_school'),
    path('ajax_update_school/', views.ajax_update_school, name='ajax_update_school'),
    path('ajax_create_school/', views.ajax_create_school, name='ajax_create_school'),
    path('ajax_get_schoollist/', views.ajax_get_schoollist, name='ajax_get_schoollist'),
    path('ajax/get-schools/', views.get_schools_by_stage, name='get_schools'),
    path('delete_last_phone/', views.delete_last_phone, name='delete_last_phone'),
    path('register_parent_category/', views.register_parent_category, name='register_parent_category'),
    path('register_category/', views.register_category, name='register_category'),
    path('register_english_word/', views.register_english_word, name='register_english_word'),
    path('get_parent_categories/', views.get_parent_categories, name='get_parent_categories'),
    path('get_categories/', views.get_categories, name='get_categories'),
    path('get_english_words/', views.get_english_words, name='get_english_words'),
    path('upload_excel/', views.upload_excel, name='upload_excel'),
    path('get_parent_categories/', views.get_parent_categories, name='get_parent_categories'),
    path('get_categories/', views.get_categories, name='get_categories'),
    path('get_english_words/', views.get_english_words, name='get_english_words'),
    path('update_parent_category/', views.update_parent_category, name='update_parent_category'),
    path('delete_parent_category/', views.delete_parent_category, name='delete_parent_category'),
    path('update_category/', views.update_category, name='update_category'),
    path('delete_category/', views.delete_category, name='delete_category'),
    path('update_english_word/', views.update_english_word, name='update_english_word'),
    path('delete_english_word/', views.delete_english_word, name='delete_english_word'),


   

    
  
]
    

classreport/urls.py
from django.urls import path
from .import views
from django.contrib.auth import views as auth_views
app_name = 'classreport'
urlpatterns = [
    path('reportcreate',views.ReportCreateView.as_view(),name='reportcreate'),
    path('teacherselect',views.TeacherSelectView.as_view(),name='teacherselect'),
    path('check_teacher_id/', views.check_teacher_id, name='check_teacher_id'),
    path('report_create/<str:teacher_id>/<str:period_id>/', views.ReportCreateView.as_view(), name='report_create'),
    path('api/teacher-schedules/', views.get_teacher_and_schedules, name='get_teacher_and_schedules'),
    path('get_period_options/', views.get_period_options, name='get_period_options'),
    path('save_report/', views.save_report, name='save_report'),
    path('get-class-schedules-report/', views.get_class_schedules, name='get_class_schedules'),
    path('get_student_subjects/<int:student_id>/', views.get_student_subjects, name='get_student_subjects'),
    path('typingpractice',views.TypingPracticeView.as_view(),name='typingpractice'),
    path('transpractice',views.TransPracticeView.as_view(),name='transpractice'),
    path('gameselect',views.GameSelectView.as_view(),name='gameselect'),
    path('api/printlist/get/', views.ajax_get_printlist, name='ajax_get_printlist'),
    path('typing/<str:pk>',views.TypingView.as_view(), name='typing'),
    path('check_student/', views.check_student_exists, name='check_student_exists'),
    path('game_clear/', views.game_clear, name='game_clear'),
    path("get_parent_categories_game/", views.get_parent_categories_game, name="get_parent_categories_game"),
    path("get_categories_game/", views.get_categories_game, name="get_categories_game"),
    path("get_english_words_game/", views.get_english_words_game, name="get_english_words_game"),
    path("get_random_wrong_trans/", views.get_random_wrong_trans, name="get_random_wrong_trans"),
    path('transquiz/<str:pk>',views.TransquizView.as_view(), name='transquiz'),
    path('trans_game_clear/', views.trans_game_clear, name='trans_game_clear'),
    path('mypagetyping/<str:pk>',views.MypageTypingView.as_view(), name='mypagetyping'),
    path('mypagetrans/<str:pk>',views.MypageTransView.as_view(), name='mypagetrans'),
    path('student_scores_view/<str:student_id>/', views.student_scores_view, name='student_scores_view'),
    path('student_scores_trans_view/<str:student_id>/', views.student_scores_trans_view, name='student_scores_trans_viewview'),

    


    

]

accountsclassroom/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser,Group,Permission

class ClassroomUser(AbstractUser):
    post=models.CharField(max_length=200,blank=True,null=True)
    groups = models.ManyToManyField(
        Group,  # Groupモデルを指定
        verbose_name='groups',
        blank=True,
        help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
        related_name="classroom_users",
        related_query_name="user"
        
    )
    user_permissions = models.ManyToManyField(
        Permission,  # Permissionモデルを指定
        verbose_name='user permissions',
        blank=True,
        help_text='Specific permissions for this user.',
        related_name="classroom_users",
        related_query_name="user"
        
    )
# Create your models here.

accountsclassroom/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import ClassroomUser

class ClassroomUserCreationForm(UserCreationForm):
    class Meta:
        model = ClassroomUser
        fields = ('username','email','password1','password2')

accountsclassroom/templates/login_classroom.html
{% extends 'baselite.html' %}
{% load static %}
{% block content %}
  
    <link rel="icon" type="imge/x-icon"
        href={% static 'assets/favicon.ico' %} />
        
    

    

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

     
      
    </style>

    
    <!-- Custom styles for this template -->
    <link href={% static "css/signin.css"%} rel="stylesheet">
</head>
    <body class="text-center">
        <main class="form-signin ">
            {% if form.errors %}
              <p style="color: red">ユーザー名とパスワードが一致しません</p>
            {% endif %}
            <form method="post" class="text-center">
            {% csrf_token %}
                <!-- <img class="mb-4"
                    src={% static "img/bootstrap-logo.svg" %}
                    alt="" width="72"
                    height="57"> -->
                <h1 class="h3 mb-3 fw-normal">教室アカウントでログイン</h1>
                <label for="Username" class="visually-hidden ">
                    User name</label>
                   
                <input type="text"
                name="username"
                id="id_username"
                maxlength="150"
                autocapitalize="none"
                autocomplete="username"
                class="form-control"
                style="width: 20rem; margin: 0 auto;"
                placeholder="ユーザー名"
                required autofocus>
            
                <label for="Password" class="visually-hidden">
                Password</label>
                <input type="password"
                name="password"
                id="id_password"
                autocomplete="current-password"
                class="form-control"
                style="width: 20rem; margin: 0 auto;"
                placeholder="パスワード"
                required autofocus>
                <input class="w-90 btn btn-lg btn-primary m-3"
                type="submit"
                value="ログイン">
               
                <br><br>
                <p><a href="{% url 'password_reset' %}">パスワードを忘れましたか</a><P>
                <!-- <p><a href="{% url 'accountsclassroom:signup_classroom' %}">新規登録</a><P> -->

                <input type="hidden"
                    name="next"
                    value="{% url 'classreport:teacherselect' %}">
            </form>
        </main>
    </body>
{% endblock %}

accountsclassroom/templates/login_classroom_game.html
{% extends 'baselite.html' %}
{% load static %}
{% block content %}
  
    <link rel="icon" type="imge/x-icon"
        href={% static 'assets/favicon.ico' %} />
        
    

    

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

     
      
    </style>

    
    <!-- Custom styles for this template -->
    <link href={% static "css/signin.css"%} rel="stylesheet">
</head>
    <body class="text-center">
        <main class="form-signin ">
            {% if form.errors %}
              <p style="color: red">ユーザー名とパスワードが一致しません</p>
            {% endif %}
            <form method="post" class="text-center">
            {% csrf_token %}
                <!-- <img class="mb-4"
                    src={% static "img/bootstrap-logo.svg" %}
                    alt="" width="72"
                    height="57"> -->
                <h1 class="h3 mb-3 fw-normal">教室アカウントでゲームにログイン</h1>
                <label for="Username" class="visually-hidden ">
                    User name</label>
                   
                <input type="text"
                name="username"
                id="id_username"
                maxlength="150"
                autocapitalize="none"
                autocomplete="username"
                class="form-control"
                style="width: 20rem; margin: 0 auto;"
                placeholder="ユーザー名"
                required autofocus>
            
                <label for="Password" class="visually-hidden">
                Password</label>
                <input type="password"
                name="password"
                id="id_password"
                autocomplete="current-password"
                class="form-control"
                style="width: 20rem; margin: 0 auto;"
                placeholder="パスワード"
                required autofocus>
                <input class="w-90 btn btn-lg btn-primary m-3"
                type="submit"
                value="ログイン">
               
                <br><br>
                <p><a href="{% url 'password_reset' %}">パスワードを忘れましたか</a><P>
                <!-- <p><a href="{% url 'accountsclassroom:signup_classroom' %}">新規登録</a><P> -->

                <input type="hidden"
                    name="next"
                    value="{% url 'classreport:gameselect' %}">
            </form>
        </main>
    </body>
{% endblock %}

accountsclassroom/templates/logout_classroom.html
{% extends 'baselite.html' %}
{% block title %}Log out{% endblock %}
    {% block content %}
    <div class="container">
        <div class="row">
            <div class="col offset-4 py-4">
            <h3>ログアウトしました</h3>
            <p><a href="{% url 'classmanager:loginselect' %}">トップページ</a><p>
        {% endblock %}

accountsclassroom/templates/password_reset_classroom.html
{% extends 'baselite.html' %}
{% block title %}Reset password{% endblock %}
    {% block content %}
    <div class="container">
        <div class="row">
            <div class="col py-4">
                <hr>
                <h3>パスワードをリセットしますか
                <p>
                登録済みのメールアドレスを入力して下さいパスワードリセットのリンクを記載したメールをすぐにお届けします
                </p>
                <br>
                <form action="" method="POST" class="text-center">
                    {% csrf_token %}
                    {{form}}
                    <input type="submit" value="メールを受け取る"/><br>
                </form>
                <br>
                <a href="{% url 'classmanager:loginselect' %}">Photo Gallery</a>
                <hr>
            </div>
        </div>
    </div>
 {% endblock %}

accountsclassroom/templates/password_reset_done_classroom.html
<!doctype html>
<html lang="ja".
    <head>
        <style>
            .pad{
                background-color: lavender;
                border: solid 2px;
                padding-top: 30px;
                padding-bottom: 50px;
                padding-left: 100px;
                margin-top: 50px;
                margin-right: 70px;
                margin-left: 70px;
                }
        </style>
    </head>
    <body>
        <div class="pad">
            <h2>パスワードがリセットされました</h2>
            <p>
            Your Password has been set. You may gto ahead and login
            </p>
            <br>
            <a href="{% url 'photo:index' %}">Photo Galleryのトップページ</a>
        </div>
    </body>
</html>

accountsclassroom/templates/password_reset_form_classroom.html
<!doctype html>
<html lang="ja">
    <head>
        <style>
            .pad{
                background-color: lavender;
                border: solid 2px;
                padding-top: 30px;
                padding-bottom: 50px;
                padding-left: 100px;
                margin-top: 50px;
                margin-right: 70px;
                margin-left: 70px;
                }
            </style>
        </head>
        <body>
            <div class="pad">
                <h2>Photo Gallery</h2>
                <h4>新しいパスワードを入力してください。これにより正しく入力できたことが確認されます</h4>
                <br />
                <form action="" method="POST">
                    {% csrf_token %}
                    {{form}}
                <input type="submit" value="パスワードリセット"/>
            </form>
        </div>
    </body>
</html>

accountsclassroom/templates/password_reset_sent_classroom.html
{% extends 'baselite.html' %}
{% block title %}Send password reset{% endblock %}
    {% block content %}
    <hr>
    <div class="container">
        <div class="row">
            <div class="col offset-2 py-4">
                <h5>パスワードのリセット手順をメールで送信しました</h5>
            <br>
            <h6>
            メールが届かない場合は登録済みのメールアドレスであるかを確認し迷惑メールフォルダも確認してください</h6>
            <br>
            <a href="{% url 'classmanager:loginselect' %}">photo Gallery</a>
        </div>
    </div>
</div>
{% endblock %}

accountsclassroom/templates/signup_classroom.html
{% extends './base.html' %}
{% block title %}Sign up{% endblock %}
    {% block content %}
    
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">      
            <h1>教室アカウントの作成</h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i>生徒</a></li>
                <li class="active">生徒一覧</li>
            </ol>
        </section>
        <section class="content">
            <div class="box">
    <div class="container ">
        <div class="row">
            <div class="col offset-2">
                <br>
                <form method = "post">
                    {% csrf_token %}
                    {% for field in form %}
                    <p>
                        {{field.label_tag}}<br>
                        {{field}}
                        {% if field.help_text %}
                        <small style="color: grey">{{field.help_text}}</small>
                        {% endif %}
                        {% for error in field.errors %}
                        <p style="color:red">{{error}}</p>
                        {% endfor %}
                    </p>
                    {% endfor %}    
                    <p style="color:red">
                        メールアドレスはパスワードをリセットする際に必要になります
                    </p>
                    <input type="submit" value="Sign up">                    
                </form>
                <br>
                <p><a href="{% url 'classmanager:loginselect' %}">
                    登録をやめてトップに戻る
                </a>
                </p>
            </div>
        </div>
    </div>
    </div>
    </section>
    {% endblock %}

accountsclassroom/templates/signup_success_classroom.html
{% extends 'baselite.html' %}
{% block title %}Registration Complete{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col offset-4 py-4">
            <h3>登録が完了しました</h3>
            <p><a href="{% url 'accountsclassroom:login_classroom' %}">ログインはこちら</a></p>
        </div>
    </div>
</div>
{% endblock %}