CMproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('classmanager.urls')),
    path('',include('accounts.urls')),
    path('',include('accountsclassroom.urls')),
    path('',include('classreport.urls')),
    path('password_reset/',
         auth_views.PasswordResetView.as_view(
             template_name="password_reset.html"),
         name='password_reset'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name="password_reset_sent.html"),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(
             template_name="password_reset_form.html"),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name="password_reset_done.html"),
         name='password_reset_complete'),
]

accounts/urls.py
from django.urls import path
from .import views
from django.contrib.auth import views as auth_views
app_name = 'accounts'
urlpatterns = [
    path('signup/',views.SignUpView.as_view(),name='signup'),
    path('signup_success/',views.SignUpSuccessView.as_view(),name='signup_success'),
    path('login',views.LoginView.as_view(),name='login'),
    path('logout/',views.LogoutView.as_view(),name='logout'),
]

accountsclassroom/urls.py
from django.urls import path
from .import views
from django.contrib.auth import views as auth_views
app_name = 'accountsclassroom'
urlpatterns = [
    path('signup_classroom/',views.SignUpClassroomView.as_view(),name='signup_classroom'),
    path('signup_success_classroom/',views.SignUpSuccessClassroomView.as_view(),name='signup_success_classroom'),
    path('login_classroom',views.LoginClassroomView.as_view(),name='login_classroom'),
    path('login_classroom_game',views.LoginClassroomGameView.as_view(),name='login_classroom_game'),
    path('logout_classroom/',views.LogoutClassroomView.as_view(),name='logout_classroom'),
]

classmanager/urls.py
from django.urls import path
from .import views

app_name='classmanager'
urlpatterns = [
    path('manager',views.IndexView.as_view(),name='manager'),
    path('',views.LoginSelectView.as_view(),name='loginselect'),
    path('assessmentlist',views.AssessmentListView.as_view(),name='assessmentlist'),
    path('setting',views.SettingView.as_view(),name='setting'),
    path('superenglishlist',views.SuperEnglishlistView.as_view(),name='superenglishlist'),
    path('studentregistration',views.StudentRegistrationView.as_view(),name='studentregistration'),
    path('studentlist',views.StudentListView.as_view(),name='studentlist'),
    path('teacherregistration',views.TeacherRegistrationView.as_view(),name='teacherregistration'),
    path('teacherlist',views.TeacherListView.as_view(),name='teacherlist'),
    path('classroomregistration',views.ClassroomRegistrationView.as_view(),name='classroomregistration'),
    path('classroomlist',views.ClassroomListView.as_view(),name='classroomlist'),
    path('lessonlist',views.LessonListView.as_view(),name='lessonlist'),
    path('timetable',views.TimetableView.as_view(),name='timetable'),
    path('api/printstudentlist/get/', views.ajax_get_printstudentlist, name='ajax_get_printstudentlist'),
    path('api/deletestudentlist/get/', views.ajax_get_deletestudentlist, name='ajax_get_deletestudentlist'),
    path('api/createstudentlist/get/', views.ajax_get_createstudentlist, name='ajax_get_createstudentlist'),
    path('api/updatastudentlist/get/', views.ajax_get_updatastudentlist, name='ajax_get_updatastudentlist'),
    path('api/updatastudentschool/get/', views.ajax_get_updatastudentschool, name='ajax_get_updatastudentschool'),
    path('ajax/delete_student_school/', views.ajax_delete_student_school, name='ajax_delete_student_school'),
    path('ajax/create_student_school/', views.ajax_create_student_school, name='ajax_create_student_school'),
    path('create_subject/', views.ajax_create_subject, name='ajax_create_subject'),
    path('ajax_get_printsubjectlist/', views.ajax_get_printsubjectlist, name='ajax_get_printsubjectlist'),
    path('ajax/get_subjects/', views.get_subjects, name='get_subjects'),
    path('ajax_get_printclassroomlist/', views.ajax_get_printclassroomlist, name='ajax_get_printclassroomlist'),
    path('ajax/create_teacher/', views.ajax_create_teacher, name='ajax_create_teacher'),
    path('ajax_get_teacherlist/', views.ajax_get_teacherlist, name='ajax_get_teacherlist'),
    path('ajax_get_update_teacher/', views.ajax_get_update_teacher, name='ajax_get_update_teacher'),
    path('ajax_get_deleteteacherlist/', views.ajax_get_deleteteacherlist, name='ajax_get_deleteteacherlist'),
    path('update-class-schedule/', views.update_class_schedule, name='update_class_schedule'),
    path('create-class-schedule/', views.create_class_schedule, name='create_class_schedule'),
    path('get-class-schedules/', views.get_class_schedules, name='get_class_schedules'),
    path('ajax_get_printtimetableoption/', views.ajax_get_printtimetableoption, name='ajax_get_printtimetableoption'),
    path('ajax/create/period/', views.ajax_create_period, name='ajax_create_period'),
    path('ajax/get/period_list/', views.ajax_get_printperiodlist, name='ajax_get_printperiodlist'),
    path('classroom_users_endpoint/', views.classroom_users_endpoint, name='classroom_users_endpoint'),
    path('api/get-reports/', views.get_reports, name='get_reports'),
    path('approve_report/', views.approve_report, name='approve_report'),
    path('update_class_schedule/', views.update_class_schedule, name='update_class_schedule'),
    path('delete_class_schedule/', views.delete_class_schedule, name='delete_class_schedule'),
    path('ajax/update-classroom/', views.update_classroom, name='update_classroom'),
    path('ajax/delete-classroom/', views.delete_classroom, name='delete_classroom'),
    path('ajax/ajax_update_subject/', views.ajax_update_subject, name='ajax_update_subject'),
    path('ajax/delete-subject/', views.delete_subject, name='ajax_delete_subject'),
    path('ajax/update_period/', views.update_period, name='update_period'),
    path('ajax/delete_period/', views.delete_period, name='delete_period'),
    path('get_student_subjects/<int:student_id>/', views.get_student_subjects, name='get_student_subjects'),
    path('get-report-detail/', views.get_report_detail, name='get_report_detail'),
    path('get-update_report/', views.update_report, name='update_report'),
    path('update_settings/', views.update_settings, name='update_settings'),
    path('schoollist/', views.SchoollistView.as_view(), name='schoollist'),
    path('ajax_delete_school/', views.ajax_delete_school, name='ajax_delete_school'),
    path('ajax_update_school/', views.ajax_update_school, name='ajax_update_school'),
    path('ajax_create_school/', views.ajax_create_school, name='ajax_create_school'),
    path('ajax_get_schoollist/', views.ajax_get_schoollist, name='ajax_get_schoollist'),
    path('ajax/get-schools/', views.get_schools_by_stage, name='get_schools'),
    path('delete_last_phone/', views.delete_last_phone, name='delete_last_phone'),
    path('register_parent_category/', views.register_parent_category, name='register_parent_category'),
    path('register_category/', views.register_category, name='register_category'),
    path('register_english_word/', views.register_english_word, name='register_english_word'),
    path('get_parent_categories/', views.get_parent_categories, name='get_parent_categories'),
    path('get_categories/', views.get_categories, name='get_categories'),
    path('get_english_words/', views.get_english_words, name='get_english_words'),
    path('upload_excel/', views.upload_excel, name='upload_excel'),
    path('get_parent_categories/', views.get_parent_categories, name='get_parent_categories'),
    path('get_categories/', views.get_categories, name='get_categories'),
    path('get_english_words/', views.get_english_words, name='get_english_words'),
    path('update_parent_category/', views.update_parent_category, name='update_parent_category'),
    path('delete_parent_category/', views.delete_parent_category, name='delete_parent_category'),
    path('update_category/', views.update_category, name='update_category'),
    path('delete_category/', views.delete_category, name='delete_category'),
    path('update_english_word/', views.update_english_word, name='update_english_word'),
    path('delete_english_word/', views.delete_english_word, name='delete_english_word'),


   

    
  
]
    

classmanager/forms.py
from django.forms import ModelForm
from .models import Student
from django import forms

class StudentForm(ModelForm):
    class Meta:
        model=Student
        fields=['name','mail','post','address']

classmanager/templates/index.html
{% extends './base.html' %}
{% block content %}
<!-- Content Wrapper. Contains page content -->


<style>
    
</style>
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>ダッシュボード</h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> ホーム</a></li>
            <li class="active">ダッシュボード</li>
        </ol>
    </section>
    
    <!-- Main content -->
    <section class="content">
        <!-- Small boxes (Stat box) -->
        <div class="row">
        
            <div class="col-lg-3 col-xs-6">
                <!-- small box -->
                <a href="{% url 'classmanager:assessmentlist' %}" class="small-box-link">
                    <div class="small-box bg-aqua">
                        <div class="inner">
                            <h4>指導評価の管理画面</h4>
                            <p>授業の様子を保護者へ配信</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-android-share"></i>
                        </div>
                        <div class="small-box-footer">
                            管理画面へ移動 <i class="fa fa-arrow-circle-right"></i>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-lg-3 col-xs-6">
                <!-- small box -->
                <a href="{% url 'classmanager:timetable' %}" class="small-box-link">
                <div class="small-box bg-aqua">
                    <div class="inner">
                        <h4>時間割の管理画面</h4>
                        <p>時間割の登録 編集</p>
                    </div>
                    <div class="icon">
                        <i class="fa fa-calendar"></i>
                    </div>
                    <div class="small-box-footer">管理画面へ移動 <i class="fa fa-arrow-circle-right"></i></div>
                </div>
            </div>
            
            <!-- ./col -->
            <div class="col-lg-3 col-xs-6">
                <!-- small box -->
                <a href="{% url 'classmanager:classroomlist' %}" class="small-box-link">
                <div class="small-box bg-primary">
                    <div class="inner">
                        <h4>教室の管理画面</h4>
                        <p>教室の登録 編集</p>
                    </div>
                    <div class="icon">
                        <i class="fa fa-group"></i>
                    </div>
                    <div class="small-box-footer">管理画面へ移動 <i class="fa fa-arrow-circle-right"></i></div>
                </div>
            </a>
            </div>
            <div class="col-lg-3 col-xs-6">
                <!-- small box -->
                <a href="{% url 'classmanager:teacherlist' %}" class="small-box-link">
                <div class="small-box bg-primary">
                    <div class="inner">
                        <h4>教師の管理画面</h4>
                        <p>教師の登録 編集</p>
                    </div>
                    <div class="icon">
                        <i class="fa fa-address-card-o"></i>
                    </div>
                    <div class="small-box-footer">管理画面へ移動 <i class="fa fa-arrow-circle-right"></i></div>
                </div>
                </a>
            </div>
            <div class="col-lg-3 col-xs-6">
                <!-- small box -->
                <a href="{% url 'classmanager:studentlist' %}" class="small-box-link">
                <div class="small-box bg-primary">
                    <div class="inner">
                        <h4>生徒の管理画面</h4>
                        <p>生徒の登録 編集</p>
                    </div>
                    <div class="icon">
                        <i class="fa fa-child"></i>
                    </div>
                    <div class="small-box-footer">管理画面へ移動 <i class="fa fa-arrow-circle-right"></i></div>
                </div>
                </a>
            </div>
            <div class="col-lg-3 col-xs-6">
                <!-- small box -->
                <a href="{% url 'classmanager:lessonlist' %}"  class="small-box-link">
                <div class="small-box bg-green">
                    <div class="inner">
                        <h4>授業の管理画面</h4>
                        <p>授業の登録 編集</p>
                    </div>
                    <div class="icon">
                        <i class="fa fa-edit"></i>
                    </div>
                    <div class="small-box-footer">管理画面へ移動 <i class="fa fa-arrow-circle-right"></i></div>
                </div>
                </a>
            </div>
            <div class="col-lg-3 col-xs-6">
                <!-- small box -->
                <a href="{% url 'classmanager:superenglishlist' %}" class="small-box-link">
                <div class="small-box bg-aqua">
                    <div class="inner">
                        <h4>ゲームの管理画面</h4>
                        <p>英単語の登録 編集</p>
                    </div>
                    <div class="icon">
                        <i class="fa fa-gamepad"></i>
                    </div>
                    <div class="small-box-footer">管理画面へ移動 <i class="fa fa-arrow-circle-right"></i></div>
                </div>
            </div>
            
        </div>
        <!-- /.row -->
        <!-- Main row -->
        <div class="row">
            <!-- Left col -->
            <section class="col-lg-7 connectedSortable">

            </section>
            <!-- /.Left col -->
            <!-- right col (We are only adding the ID to make the widgets sortable)-->
            <!-- right col -->
        </div>
        <!-- /.row (main row) -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->
{% endblock content %}

classmanager/templates/loginselect.html
{% extends 'baselite.html' %}
{% block title %}Registration Complete{% endblock %}
{% load static %}
{% block content %}
<style>
    .menu {
    display: flex;
    text-align: center;
    width: 100%; /* 親要素に合わせる */
}
.menuselect{
    width: 100%;
    margin: 5px;
}

@media screen and (max-width: 1024px) {
    .menu {
        flex-direction: column;
        flex-direction: column;  /* 縦方向に並べる */
  justify-content: center; /* 縦方向（main axis）で中央に配置 */
  align-items: center;
        
    }
}


</style>
<div class="text-center m-5">
    <h1 class="text-anchor">ログイン一覧</h1>
</div>
<div class="menu container-fluid">

  
    <div class=" menuselect border border-opacity-50 border-2 border-secondary rounded-2">
        
                <div class="text-center mt-5">
                    <img src="{% static "img/apple-touch-icon-100x100.png" %}" alt="freee会計" width="100" height="100" >
                    <h class="display-2">教室ログイン</h>
                </div>
            
            <div class="text-center my-5">
                <a class="btn btn-primary btn-lg w-75 m-1" href="{% url 'accountsclassroom:login_classroom' %}" >受業を開始する</a><br>
                <a class="btn btn-primary btn-lg w-75 m-1" href="{% url 'accountsclassroom:login_classroom_game' %}" >ゲームを開始する</a>

            </div>
        </div>
    
        
       
    <div class="menuselect border border-opacity-50 border-2 border-secondary  rounded-2">
        
                <div class="text-center mt-5">
                    <img src="{% static "img/apple-touch-icon-100x100.png" %}" alt="freee会計" width="100" height="100" >
                    <h class="display-2">管理者ログイン</h>

                </div>

         
            <div class="text-center my-5">
                <a class="btn btn-primary btn-lg w-75" href="{% url 'accounts:login' %}" >ログインする</a>
            </div>

        </div>

    </div>



{% endblock %}

classmanager/templates/schoollist.html
{% extends './base.html' %}
{% block content %}
<!-- Content Wrapper. Contains page content -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
 
<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
 

    
<style>
.content-wrapper{
  
}
.content{
    
}
.form{
    border: 5px solid #fafafa;
  padding: 1em;
    width: 100%;
  text-align: center;
  background-color: #ffffff;
}

.school_table{
    border: 5px solid #fafafa;
    padding: 1em;
    text-align: center;
    background-color: #ffffff;
  
}
.school_table{
    border: 5px solid #fafafa;
    padding: 1em;
    text-align: center;
    background-color: #ffffff;
  
}


.school_th{
    border: 2px solid #fafafa;
    background-color: #c2c1c1;
   
    
}
.school_td{
    
    border-bottom: 1px solid #b0b0b0;
    border-right: 2px solid #ffffff;
   background-color: #fafafa;
   height: 15px;
}
.school_title{
    width: 10%;
    min-width: 70px;
}
.school_stage{
    width: 10%;
    min-width: 70px;
}
.period_end_time{
    width: 10%;
    min-width: 70px;
}
.period_check{
    width: 10%;
    min-width: 70px;
}

.subject_th{
    border: 2px solid #fafafa;
    background-color: #c2c1c1;
   
    
}
.subject_td{
    
    border-bottom: 1px solid #b0b0b0;
    border-right: 2px solid #ffffff;
   background-color: #fafafa;
   height: 15px;
   
}
.red_td{
    background-color: #f7e7db;
}
.blue_td{
    background-color: #d9eef3;
}
.school_check{
    width:5%;
    min-width: 25px;
}
.subject_title{
    width: 10%;
    min-width: 70px;
}

.approval_button{
    position:absolute;
    top: 60%;
    right: 1%;
    width: 7%;
}
.detail_button{
    position:absolute;
    top: 20%;
    right: 1%;
    width: 7%;
}
.lesson_data{
    position:absolute;
    top: 5%;
    left: 1%;
    width: 100%;
}
.active_box{
    display: none;
}

    .student_table:hover {
        background-color: #252323; /* マウスオーバー時の背景色 */
    }
</style><div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>学校一覧</h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-edit"></i>学校</a></li>
            <li class="active">学校一覧</li>
        </ol>
    </section>
    <section class="content">
        <div class="box">
            <form method="POST">
                <div>
                    <label for="form_school_title">学校名 <span class="text-sm text-danger">必須</span></label>
                    <input type="text" required value="" name="form_school_title" id="form_school_title">                     
                </div>
                <div>
                    <select name="form_school_stage" id="form_school_stage">
                        <option value="小学生">小学生</option>
                        <option value="中学生">中学生</option>
                        <option value="高校生">高校生</option>
                        <option value="大学生">大学生</option>
                        <option value="その他">その他</option>
                    </select>
                </div>
                <input type="button" value="保存" class="btn btn-primary" onclick="createSchool()">
            </form>
        </div>
        <div class="assessment_box">
            <table class="school_table" style="border-collapse:collapse;border:none;">
                <thead>
                    <tr>
                        <td class="school_th school_check">
                            <input type="checkbox" id="school_check" name="school_check">
                        </td>
                        <td class="school_th school_name">
                            学校名
                        </td>
                        <td class="school_th school_stage">
                            教育段階
                        </td>
                    </tr>
                </thead>
            </table>
            <div id="school-list">
                <!-- JavaScript will insert rows here -->
            </div>
        </div>
    </section>
</div>
<script>
function loadSchoolList() {
    $.ajax({
        url: '{% url "classmanager:ajax_get_schoollist" %}', // Set this to your URL endpoint
        type: 'GET',
    }).done(response => {
        const schoolListDiv = document.getElementById('school-list');
        schoolListDiv.innerHTML = ''; // Clear current list
        response.schools.forEach((school) => {
            const row = document.createElement('div');
            row.setAttribute('data-school-id', school.pk);
            row.innerHTML = `
                <table class="school_table" style="border-collapse:collapse;border:none;">
                    <tr>
                        <td class="school_td school_check">
                            <input type="checkbox">
                        </td>
                        <td class="school_td school_name">${school.fields.name}</td>
                        <td class="school_td school_stage">${school.fields.stage}</td>
                    </tr>
                </table>
                <div class="active_box box" style="display: none;">
                    <form>
                        <div>
                            <label for="form_school_name">学校名</label>
                            <input type="text" required value="${school.fields.name}" name="form_school_name" id="form_school_name_${school.pk}">
                        </div>
                        <div>
                            <label for="form_school_stage">教育段階</label>
                            <select required name="form_school_stage" id="form_school_stage_${school.pk}">
                                <option value="小学生" ${school.fields.stage === "小学生" ? "selected" : ""}>小学生</option>
                                <option value="中学生" ${school.fields.stage === "中学生" ? "selected" : ""}>中学生</option>
                                <option value="高校生" ${school.fields.stage === "高校生" ? "selected" : ""}>高校生</option>
                                <option value="大学生" ${school.fields.stage === "大学生" ? "selected" : ""}>大学生</option>
                                <option value="その他" ${school.fields.stage === "その他" ? "selected" : ""}>その他</option>
                            </select>
                        </div>
                        <div>
                            <input type="button" value="保存" class="btn btn-primary" onclick="updateSchool(${school.pk})">
                            <input type="button" value="削除" class="btn btn-danger" onclick="deleteSchool(${school.pk})">
                        </div>
                    </form>
                </div>
            `;
            schoolListDiv.appendChild(row);
        });
        addTableListeners();
    });
}

function createSchool() {
    const name = document.getElementById('form_school_title').value;
    const stage = document.getElementById('form_school_stage').value;
    if (!name || !stage) {
        alert('学校名と教育段階を入力してください。');
        return;
    }
    $.ajax({
        url: '{% url "classmanager:ajax_create_school" %}', // Set this to your URL endpoint
        type: 'POST',
        headers: {
            'X-CSRFToken': '{{ csrf_token }}',
        },
        data: JSON.stringify({ name, stage }),
        contentType: 'application/json',
        success: function(response) {
            if (response.success) {
                alert('学校情報が保存されました。');
                loadSchoolList();
            } else {
                alert('保存に失敗しました。');
            }
        },
        error: function() {
            alert('通信エラーが発生しました。');
        }
    });
}

function updateSchool(schoolId) {
    const name = document.getElementById(`form_school_name_${schoolId}`).value;
    const stage = document.getElementById(`form_school_stage_${schoolId}`).value;
    $.ajax({
        url: '{% url "classmanager:ajax_update_school" %}', // Set this to your URL endpoint
        type: 'POST',
        headers: {
            'X-CSRFToken': '{{ csrf_token }}',
        },
        data: JSON.stringify({ school_id: schoolId, name, stage }),
        contentType: 'application/json',
        success: function(response) {
            if (response.success) {
                alert('学校情報が更新されました。');
                loadSchoolList();
            } else {
                alert('更新に失敗しました。');
            }
        },
        error: function() {
            alert('通信エラーが発生しました。');
        }
    });
}

function deleteSchool(schoolId) {
    $.ajax({
        url: '{% url "classmanager:ajax_delete_school" %}', // Set this to your URL endpoint
        type: 'POST',
        headers: {
            'X-CSRFToken': '{{ csrf_token }}',
        },
        data: JSON.stringify({ school_id: schoolId }),
        contentType: 'application/json',
        success: function(response) {
            if (response.success) {
                alert('学校情報が削除されました。');
                loadSchoolList();
            } else {
                alert('削除に失敗しました。');
            }
        },
        error: function() {
            alert('通信エラーが発生しました。');
        }
    });
}

function addTableListeners() {
    const tables = document.querySelectorAll('.school_table');
    tables.forEach(function(table) {
        table.addEventListener('click', function() {
            const form = table.nextElementSibling;
            if (form && form.classList.contains('active_box')) {
                const isVisible = form.style.display === 'block';
                document.querySelectorAll('.active_box').forEach(function(box) {
                    box.style.display = 'none';
                });
                form.style.display = isVisible ? 'none' : 'block';
            }
        });
    });
}

// Load the school list when page loads
loadSchoolList();
</script>


{% endblock content %}

classmanager/templates/title.html
<style>
  .btn-custom{
    background-color: #faa63e;
    color: white;
  }
  .btn-custom:hover {
    background-color: #faa80e;
    color: #ffffff;
  }
.fieldtitle {

  display: flex;
  align-items: center;
  justify-content: center;
  margin: auto;
  color: #5c5e82;
  }
</style>
  <section class=" text-center container">
    <div class="py-2">
      <div class="">
       
        
        
        {% if user.is_authenticated %}

        <a href="{% url 'accounts:logout' %}" class="btn btn-primary my-2">ログアウト</a> 
        {% else %}
        <p class="lead text-muted">ログインしてテストの結果を記録しましょう</p>
        <p>
        <a href="{% url 'accounts:signup' %}"
            class="btn btn-primary my-2">教室新規登録</a>
        <a href="{% url 'accounts:login' %}"
            class="btn btn-secondary my-2">教室IDまたは管理者IDでログイン</a>
        {% endif %}
        </p>
      </div>
    </div>
    <div class='fieldtitle'>
      <h2 id='id_name' class=''>タイピング練習</h2>
      
      </div>
  </section>

 